# Generated by Django 5.0.6 on 2024-06-02 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(choices=[('XIAOMI', 'Xiaomi'), ('SAMSUNG', 'Samsung'), ('APPLE', 'Apple')], max_length=20)),
                ('precio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('especificaciones', models.CharField(max_length=300)),
                ('foto', models.ImageField(null=True, upload_to='celulares')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
