# Generated by Django 5.0.6 on 2024-06-22 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(choices=[('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung')], max_length=20)),
                ('precio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('especificaciones', models.CharField(max_length=500)),
                ('foto', models.ImageField(null=True, upload_to='celulares')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('num_departamento', models.CharField(blank=True, max_length=10, verbose_name='N° de departamento (si aplica)')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
