# Generated by Django 5.0.6 on 2024-06-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0002_usuario_apellido_usuario_nombre_alter_celular_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_departamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='celular',
            name='especificaciones',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Nombre de usuario'),
        ),
    ]
