# Generated by Django 5.0.6 on 2024-06-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0002_alter_celular_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='customuser',
            name='comuna',
            field=models.CharField(default='Comuna', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(default='Direccion', max_length=255, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_departamento',
            field=models.CharField(blank=True, max_length=10, verbose_name='N° de departamento (si aplica)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default='Region', max_length=100, verbose_name='Región'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='rut',
            field=models.CharField(default='Rut', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default='Telefono', max_length=20, verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung')], max_length=20),
        ),
    ]
