# Generated by Django 5.0.6 on 2024-06-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0003_rename_first_name_customuser_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='a', max_length=50, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=20),
        ),
    ]
