# Generated by Django 5.0.6 on 2024-06-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0004_customuser_username_alter_celular_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung')], max_length=20),
        ),
    ]
