# Generated by Django 5.0.6 on 2024-06-25 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0005_alter_celular_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mobilemart.carrito')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Samsung', 'Samsung'), ('Apple', 'Apple')], max_length=20),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='celular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilemart.celular'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='celulares',
            field=models.ManyToManyField(through='mobilemart.ItemCarrito', to='mobilemart.celular'),
        ),
    ]
