# Generated by Django 5.0.6 on 2024-06-26 23:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemart', '0006_carrito_itemcarrito_delete_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='marca',
            field=models.CharField(choices=[('Xiaomi', 'Xiaomi'), ('Apple', 'Apple'), ('Samsung', 'Samsung')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilemart.celular')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mobilemart.pedido')),
            ],
        ),
    ]
